# Welcome to Jekyll!
#

# Site settings
title: Tangbo Surf House
description: |
  Come surf in northern Siargao
owner: Tangbo Surf House # or company name
first_published: 2025 # if migrating another site, the year of your first publish
email: tangbosurfhouse@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tangbosurfhouse.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #email: tangbosurfhouse@gmail.com
  instagram: https://www.instagram.com/tangbosurfhouse
  #youtube-square:
  #spotify:
  #vimeo:
  #reddit:
  #trello:
  #foursquare:
  #vk:
  #yelp:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
